package report

import (
	"fmt"
	"strings"

	"github.com/spectre/spectre/internal/storage"
)

// GenerateMarkdownReport creates a comprehensive investigation report in Markdown format.
func GenerateMarkdownReport(caseID string) (string, error) {
	c, err := storage.GetCase(caseID)
	if err != nil {
		return "", err
	}
	if c == nil {
		return "", fmt.Errorf("case not found")
	}

	entities, _ := storage.ListEntitiesByCase(caseID)
	rels, _ := storage.ListRelationshipsByCase(caseID)
	timeline, _ := storage.GetCaseTimeline(caseID)
	analysis, _ := storage.GetLatestAnalysis(caseID)

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# 🕵️ SPECTRE Investigation Report: %s\n\n", escapeMarkdown(c.Name)))
	sb.WriteString(fmt.Sprintf("**Case ID:** `%s`  \n", c.ID))
	sb.WriteString(fmt.Sprintf("**Status:** %s  \n", escapeMarkdown(c.Status)))
	sb.WriteString(fmt.Sprintf("**Description:** %s\n\n", escapeMarkdown(c.Description)))

	if analysis != nil {
		sb.WriteString("## 🧠 AI Intelligence Synthesis\n")
		sb.WriteString(fmt.Sprintf("**Confidence:** %.2f\n\n", analysis.Confidence))
		
		sb.WriteString("### Key Findings\n")
		for _, f := range analysis.Findings {
			sb.WriteString(fmt.Sprintf("- %s\n", escapeMarkdown(f)))
		}
		sb.WriteString("\n### Identified Risks\n")
		for _, r := range analysis.Risks {
			sb.WriteString(fmt.Sprintf("- %s\n", escapeMarkdown(r)))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("## 📊 Entity Graph Summary\n")
	sb.WriteString(fmt.Sprintf("- **Total Entities:** %d\n", len(entities)))
	sb.WriteString(fmt.Sprintf("- **Total Relationships:** %d\n\n", len(rels)))

	sb.WriteString("### Discovered Entities\n")
	sb.WriteString("| Type | Value | Source |\n")
	sb.WriteString("|------|-------|--------|\n")
	for _, e := range entities {
		sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", escapeMarkdown(e.Type), escapeMarkdown(e.Value), escapeMarkdown(e.Source)))
	}
	sb.WriteString("\n")

	sb.WriteString("## 📅 Investigation Timeline\n")
	for _, ev := range timeline {
		ts := ev.Timestamp.Format("2006-01-02 15:04:05")
		sb.WriteString(fmt.Sprintf("**%s** - *%s*\n", ts, escapeMarkdown(ev.Type)))
		sb.WriteString(fmt.Sprintf("> %s (Source: %s)\n\n", escapeMarkdown(ev.Description), escapeMarkdown(ev.Source)))
	}

	sb.WriteString("\n---\n*Generated by SPECTRE CLI*")

	return sb.String(), nil
}

// escapeMarkdown escapes common Markdown characters to prevent injection.
func escapeMarkdown(text string) string {
	replacer := strings.NewReplacer(
		"*", "\\*",
		"_", "\\_",
		"`", "\\`",
		"[", "\\[",
		"]", "\\]",
		"<", "&lt;",
		">", "&gt;",
		"|", "\\|", // Important for tables
	)
	return replacer.Replace(text)
}
